[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bidlock = "23zkP27qb2eNg1nxKovh3zTLiLKXccKoRHRH6wukMYEs"

[programs.devnet]
bidlock = "23zkP27qb2eNg1nxKovh3zTLiLKXccKoRHRH6wukMYEs"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
